# Generated by Django 2.0 on 2018-02-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180224_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='send_notifications',
            field=models.BooleanField(default=True, verbose_name='Send notification emails'),
        ),
    ]
