# Generated by Django 2.0 on 2018-02-27 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0010_userprofile_send_notifications")]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
                ("img_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.Category",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separates list of tags",
                max_length=128,
                null=True,
                verbose_name="Keyword Tags",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="topics",
            field=models.ManyToManyField(blank=True, to="events.Topic"),
        ),
        migrations.AddField(
            model_name="team",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.Category",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="topics",
            field=models.ManyToManyField(blank=True, to="events.Topic"),
        ),
    ]
