# Generated by Django 2.0 on 2018-03-07 17:37

from django.db import migrations, models
import pytz

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20180304_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchable',
            name='event_uri',
            field=models.CharField(max_length=256, null=True, serialize=False),
        ),
    ]
