# Generated by Django 2.0 on 2018-03-24 02:55

import datetime

import django.db.models.deletion
from django.db import migrations, models

import mptt.fields


class Migration(migrations.Migration):

    dependencies = [("events", "0019_add_org_slug")]

    operations = [
        migrations.CreateModel(
            name="EventComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "created_time",
                    models.DateTimeField(db_index=True, default=datetime.datetime.now),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(-1, "Removed"), (0, "Pending"), (1, "Approved")],
                        db_index=True,
                        default=1,
                    ),
                ),
                ("lft", models.PositiveIntegerField(db_index=True, editable=False)),
                ("rght", models.PositiveIntegerField(db_index=True, editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="eventcomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.UserProfile"
            ),
        ),
        migrations.AddField(
            model_name="eventcomment",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.Event"
            ),
        ),
        migrations.AddField(
            model_name="eventcomment",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="events.EventComment",
            ),
        ),
    ]
