# Generated by Django 2.0 on 2018-04-14 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20180404_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Event Name')),
                ('recurrences', recurrence.fields.RecurrenceField(null=True)),
                ('last_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time of the last created instance in this series')),
                ('start_time', models.TimeField(db_index=True, help_text='Date and time that the event starts', verbose_name='Start Time')),
                ('end_time', models.TimeField(db_index=True, help_text='Date and time that the event ends', verbose_name='End Time')),
                ('summary', models.TextField(blank=True, help_text='Summary of the Event', null=True)),
                ('created_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='the date and time when the event was created')),
                ('tags', models.CharField(blank=True, max_length=128, null=True, verbose_name='Keyword Tags')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.UserProfile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_events', to='events.CommonEvent')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Place')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Team')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='events.EventSeries'),
        ),
    ]
