# Generated by Django 2.0 on 2018-04-27 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0028_add_speaker_models")]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="team",
            name="premium_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="premium_teams",
                to="events.UserProfile",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="premium_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="premium_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="talk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presentations",
                to="events.Talk",
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Biography"),
        ),
        migrations.AlterField(
            model_name="talk",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="talks",
                to="events.Speaker",
                verbose_name="Speaker Bio",
            ),
        ),
    ]
