# Generated by Django 2.0 on 2018-05-19 02:10

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_add_attendee_actual_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Sponsor Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('web_url', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Will be scaled and cropped to max 250x200 px.', upload_to='sponsors', verbose_name='Sponsor Logo')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(related_name='events', to='events.Sponsor'),
        ),
        migrations.AddField(
            model_name='team',
            name='sponsors',
            field=models.ManyToManyField(related_name='teams', to='events.Sponsor'),
        ),
    ]
