# Generated by Django 2.0 on 2018-06-10 15:31

from django.db import migrations, models

import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [("events", "0032_add_team_slug")]

    operations = [migrations.RemoveField(model_name="team", name="cover_img")]
