# Generated by Django 2.0 on 2018-06-10 15:34

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_remove_unused_team_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='team_covers', verbose_name='Cover Image'),
        ),
    ]
