# Generated by Django 2.0 on 2018-07-29 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0037_add_org_details")]

    operations = [
        migrations.AddField(
            model_name="commonevent",
            name="continent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.Continent",
            ),
        )
    ]
