# Generated by Django 2.0 on 2018-08-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0038_add_common_event_continent")]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="do_not_track",
            field=models.BooleanField(default=False, verbose_name="Do not track"),
        )
    ]
