# Generated by Django 2.0 on 2018-08-05 17:58

import datetime
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0039_add_profile_privacy_option")]

    operations = [
        migrations.CreateModel(
            name="OrgTeamRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_origin",
                    models.SmallIntegerField(
                        choices=[(0, "Organization"), (1, "Team")],
                        db_index=True,
                        default=0,
                        verbose_name="Request from",
                    ),
                ),
                ("request_key", models.UUIDField(default=uuid.uuid4)),
                ("requested_date", models.DateTimeField(default=datetime.datetime.now)),
                ("joined_date", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_org_memberships",
                        to="events.UserProfile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.Organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_org_memberships",
                        to="events.UserProfile",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="sponsors",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="events.Sponsor"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="premium_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="premium_teams",
                to="events.UserProfile",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="sponsors",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to="events.Sponsor"
            ),
        ),
        migrations.AddField(
            model_name="orgteamrequest",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.Team"
            ),
        ),
    ]
