# Generated by Django 2.0 on 2018-08-11 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_add_org_membership_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='access',
            field=models.SmallIntegerField(choices=[(0, 'Public'), (1, 'Personal'), (2, 'Private')], default=0, verbose_name='Access'),
        ),
        migrations.AlterField(
            model_name='orgteamrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_org_memberships', to='events.UserProfile'),
        ),
    ]
