# Generated by Django 2.0 on 2018-08-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_remove_premium_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enable_comments',
            field=models.BooleanField(default=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_photos',
            field=models.BooleanField(default=True, verbose_name='Photos'),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_presentations',
            field=models.BooleanField(default=False, verbose_name='Presentations'),
        ),
    ]
