# Generated by Django 2.0 on 2018-09-26 22:14

from django.db import migrations

import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [("events", "0045_change_field_help_text")]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="logo",
            field=imagekit.models.fields.ProcessedImageField(
                help_text="Will be scaled and cropped to max 250x200 px.",
                upload_to="sponsors",
                verbose_name="Logo",
            ),
        )
    ]
