# Generated by Django 2.0.8 on 2019-01-02 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0048_add_photo_uploader")]

    operations = [
        migrations.AddField(
            model_name="eventcomment",
            name="updated_time",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        )
    ]
