# Generated by Django 2.0.12 on 2019-07-01 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0049_add_comment_updated_time")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendee_limit",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="If set, will limit the number of people who can register as attending your event.",
                null=True,
                verbose_name="Attendee Limit",
            ),
        ),
        migrations.AddField(
            model_name="eventseries",
            name="attendee_limit",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="If set, will limit the number of people who can register as attending your event.",
                null=True,
                verbose_name="Attendee Limit",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.Category",
            ),
        ),
    ]
